apiVersion: v1
kind: Service
metadata:
  # finalizers:
  # - service.kubernetes.io/load-balancer-cleanup
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: psm-tenent-backup-svc-1
  name: psm-tenent-backup-svc-1
  # namespace: default
  namespace: psm-svc203-ns
spec:
  # allocateLoadBalancerNodePorts: true
  # externalTrafficPolicy: Cluster
  # internalTrafficPolicy: Cluster
  # ipFamilies:
  # - IPv4
  # ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tenent-backup-p
    port: 8080
    protocol: TCP
    targetPort: tenent-backup-p
  selector:
    app: psm-tenent-backup
  sessionAffinity: None
  type: LoadBalancer